CREATE DATABASE todo;

CREATE TABLE users (
    Name VARCHAR(50) NOT NULL,
    Email VARCHAR(50) NOT NULL UNIQUE,
    Password VARCHAR(50) NOT NULL
);

CREATE TABLE Cards (
    title VARCHAR(50) NOT NULL,
    description VARCHAR(255) NOT NULL UNIQUE,
    tag VARCHAR(50) NOT NULL DEFAULT 'General',
    Date DATE DEFAULT CURRENT_DATE
);